import Link from "next/link";
import { ArrowRight, FilePlus2, Files, Hourglass } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

export default async function FacultyDashboard() {
  const supabase = await createClient();
  const { data: { user } } = supabase ? await supabase.auth.getUser() : { data: { user: null } };
  const { count: total } = supabase ? await supabase.from("resources").select("id", { count: "exact", head: true }).eq("uploaded_by", user!.id) : { count: null };
  const { count: pending } = supabase ? await supabase.from("resources").select("id", { count: "exact", head: true }).eq("uploaded_by", user!.id).eq("status", "pending_review") : { count: null };
  const { data: recent } = supabase ? await supabase.from("resources").select("id, title, status, created_at, subjects(name)").eq("uploaded_by", user!.id).order("created_at", { ascending: false }).limit(6) : { data: [] };
  return <div className="dashboard-page"><div className="dashboard-top"><div><span className="eyebrow">FACULTY PORTAL</span><h1>Good morning{user?.user_metadata?.full_name ? `, ${user.user_metadata.full_name.split(" ")[0]}` : ""}.</h1><p>Thank you for making great course material easier to find.</p></div><Link className="button button-dark" href="/faculty/resources/new"><FilePlus2 size={16} /> Add a resource</Link></div><div className="dashboard-stats"><article><span><Files size={17} /></span><small>YOUR RESOURCES</small><strong>{total ?? 0}</strong></article><article><span><Hourglass size={17} /></span><small>AWAITING REVIEW</small><strong>{pending ?? 0}</strong></article><article><span><ArrowRight size={17} /></span><small>PUBLIC LIBRARY</small><strong>Open</strong></article></div><div className="dashboard-table-head"><div><span className="eyebrow">RECENT ACTIVITY</span><h2>Your uploads</h2></div><Link className="text-link" href="/faculty/resources">View all <ArrowRight size={14} /></Link></div><div className="resource-table">{recent?.map((resource) => <div className="resource-table-row" key={resource.id}><span className="table-file"><Files size={15} /></span><span className="table-title"><strong>{resource.title}</strong><small>{(resource.subjects as unknown as { name: string } | null)?.name ?? "Subject"}</small></span><span className={`status-pill status-${resource.status}`}>{resource.status.replaceAll("_", " ")}</span><span className="table-date">{new Date(resource.created_at).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</span></div>)}{!recent?.length && <div className="empty-dashboard"><Files size={24} /><h3>Your resource shelf is empty</h3><p>Upload a PDF for an assigned subject. It’ll enter the review queue before students can see it.</p><Link className="text-link" href="/faculty/resources/new">Add your first resource <ArrowRight size={14} /></Link></div>}</div></div>;
}
